services:
  loki-lite:
    build:
      context: ..
      target: production
    restart: unless-stopped
    group_add:
      - "101"  # systemd-journal
    volumes:
      - /var/log/journal:/var/log/journal:ro
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./provisioning:/etc/grafana/provisioning
